from fastapi import APIRouter

from app.api.routes import ai, execution, health, intelligence, live, market, market_chart, polarium, polarium_diagnostics, polarium_direct, polarium_oauth, polarium_session_inspector, polarium_ws_recorder, providers, quadcode, risk, scanner, signal, system

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(system.router)
api_router.include_router(market.router)
api_router.include_router(market_chart.router)
api_router.include_router(ai.router)
api_router.include_router(risk.router)
api_router.include_router(providers.router)
api_router.include_router(providers.manager_router)
api_router.include_router(polarium.router)
api_router.include_router(polarium_direct.router)
api_router.include_router(polarium_oauth.router)
api_router.include_router(polarium_diagnostics.router)
api_router.include_router(polarium_session_inspector.router)
api_router.include_router(polarium_ws_recorder.router)
api_router.include_router(quadcode.router)
api_router.include_router(signal.router)
api_router.include_router(intelligence.router)
api_router.include_router(scanner.router)
api_router.include_router(execution.router)
api_router.include_router(live.router)
