from __future__ import annotations

from typing import Protocol

from app.market.events.models import NormalizedMarketCandle
from app.market.persistence.models import PersistenceCleanupResult, PersistenceWriteResult


class CandlePersistenceRepository(Protocol):
    def initialize(self) -> None: ...

    def upsert(self, candle: NormalizedMarketCandle) -> PersistenceWriteResult: ...

    def load_all(self) -> tuple[NormalizedMarketCandle, ...]: ...

    def prune_retention(self, active_id: int, raw_size: int, limit: int) -> int: ...

    def prune_retention_by_series_key(self, series_key: str, limit: int) -> int: ...

    def clear(self) -> PersistenceCleanupResult: ...

    def count_candles(self) -> int: ...

    def count_series(self) -> int: ...

    def sanitized_path(self) -> str: ...
