from __future__ import annotations

POCKET_PROVIDER_DISABLED = "POCKET_PROVIDER_DISABLED"
POCKET_LIVE_CONNECTION_DISABLED = "POCKET_LIVE_CONNECTION_DISABLED"
POCKET_TRANSPORT_NOT_RUNNING = "POCKET_TRANSPORT_NOT_RUNNING"
POCKET_EVENT_INVALID = "POCKET_EVENT_INVALID"
POCKET_ASSET_MISSING = "POCKET_ASSET_MISSING"
POCKET_PERIOD_MISSING = "POCKET_PERIOD_MISSING"
POCKET_PERIOD_UNSUPPORTED = "POCKET_PERIOD_UNSUPPORTED"
POCKET_HISTORY_INVALID = "POCKET_HISTORY_INVALID"
POCKET_TICK_INVALID = "POCKET_TICK_INVALID"
POCKET_STORE_WRITE_FAILED = "POCKET_STORE_WRITE_FAILED"
POCKET_READ_ONLY_GUARD_BLOCKED = "POCKET_READ_ONLY_GUARD_BLOCKED"
POCKET_UNKNOWN_EVENT = "POCKET_UNKNOWN_EVENT"
POCKET_RUNTIME_ERROR = "POCKET_RUNTIME_ERROR"


class PocketRuntimeError(Exception):
    """Controlled Pocket runtime error with a sanitized code."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message

